// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrH-ABTzSJEpfKjAcMzrHUGvcIA2x7cLo',
    appId: '1:146074444448:web:b9d5b29cd901ef038a5fc5',
    messagingSenderId: '146074444448',
    projectId: 'todolist-e1f6b',
    authDomain: 'todolist-e1f6b.firebaseapp.com',
    storageBucket: 'todolist-e1f6b.appspot.com',
    measurementId: 'G-3MWBBMS75M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWdwVByaSAEEZPd6O7rAlIOi3pm8GYTo',
    appId: '1:146074444448:android:dd5524f2c30135e48a5fc5',
    messagingSenderId: '146074444448',
    projectId: 'todolist-e1f6b',
    storageBucket: 'todolist-e1f6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqV4Z-yXFnsn03441wLDVLtT0BIpWNtG8',
    appId: '1:146074444448:ios:272d07d64c61fe028a5fc5',
    messagingSenderId: '146074444448',
    projectId: 'todolist-e1f6b',
    storageBucket: 'todolist-e1f6b.appspot.com',
    iosClientId: '146074444448-b6ppgmcrefuto0vi5i70js4s55ikkplj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqV4Z-yXFnsn03441wLDVLtT0BIpWNtG8',
    appId: '1:146074444448:ios:272d07d64c61fe028a5fc5',
    messagingSenderId: '146074444448',
    projectId: 'todolist-e1f6b',
    storageBucket: 'todolist-e1f6b.appspot.com',
    iosClientId: '146074444448-b6ppgmcrefuto0vi5i70js4s55ikkplj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}